const cursos = [
  { id: "estrategias", nombre: "Estrategias para el aprendizaje", prereq: [] },
  { id: "antropologia", nombre: "Antropología", prereq: [] },
  { id: "etica", nombre: "Ética", prereq: ["antropologia"] },
  { id: "biologia", nombre: "Fund. Biológicos del comportamiento", prereq: [] },
  { id: "neuro", nombre: "Neuropsicología", prereq: ["biologia"] },
  { id: "cognitivos", nombre: "Procesos Cognitivos", prereq: [] },
  { id: "evolutiva1", nombre: "Psicología Evolutiva I", prereq: ["cognitivos", "afectivos"] },
  { id: "personalidad", nombre: "Psicología de la Personalidad", prereq: ["cognitivos", "afectivos"] },
  { id: "evolucion", nombre: "Evolución histórica de la psicología", prereq: [] },
  { id: "teorias1", nombre: "Teorías Psicológicas I", prereq: ["evolucion"] },
  { id: "teorias2", nombre: "Teorías Psicológicas II", prereq: ["evolucion"] },
  { id: "filosofia", nombre: "Fund. Filosóficos de la psicología", prereq: [] },
  { id: "comunicacion", nombre: "Taller de comunicación", prereq: [] },
  { id: "afectivos", nombre: "Procesos Afectivos", prereq: [] },
  { id: "grupo", nombre: "Taller de trabajo grupal", prereq: [] },
  { id: "socioantropo", nombre: "Fund. Socioantropológicos", prereq: [] },
  { id: "introinvest", nombre: "Intro. metodología investigación", prereq: [] },
  { id: "investaplicada", nombre: "Investigación aplicada psicología", prereq: ["introinvest"] },
  { id: "electivo1", nombre: "Electivo Formación Integral I", prereq: ["etica"] },
  { id: "electivo2", nombre: "Electivo Formación Integral II", prereq: [] },
  { id: "electivo3", nombre: "Electivo Formación Integral III", prereq: [] },
  { id: "electivo4", nombre: "Electivo Formación Integral IV", prereq: [] },
  { id: "entrevista", nombre: "Taller de entrevista", prereq: [] },
  { id: "social1", nombre: "Psicología Social I", prereq: [] },
  { id: "social2", nombre: "Psicología Social II", prereq: ["social1"] },
  { id: "cuantitativos", nombre: "Análisis Datos Cuantitativos", prereq: ["investaplicada"] },
  { id: "cualitativos", nombre: "Análisis Datos Cualitativos", prereq: ["investaplicada"] },
  { id: "proyectos", nombre: "Formulación Proyectos Sociales", prereq: ["investaplicada"] },
  { id: "psicopatogen", nombre: "Psicopatología General", prereq: ["personalidad"] },
  { id: "infantil", nombre: "Psicopatología Infantil", prereq: ["psicopatogen"] },
  { id: "adulto", nombre: "Psicopatología Adulto", prereq: ["psicopatogen"] },
  { id: "evalcognitiva", nombre: "Evaluación Psic. Cognitiva", prereq: ["neuro"] },
  { id: "evalpersonalidad", nombre: "Evaluación Psic. Personalidad", prereq: ["evalcognitiva"] },
  { id: "evalintegrada", nombre: "Evaluación Psic. Integrada", prereq: ["evalpersonalidad"] },
  { id: "tallerpersona", nombre: "Taller Persona del Psicólogo", prereq: ["evalpersonalidad"] },
  { id: "politicas", nombre: "Políticas Públicas", prereq: [] },
  { id: "sistemica", nombre: "Psicoterapia Sistémica", prereq: ["teorias1"] },
  { id: "psicoanalitica", nombre: "Psicoterapia Psicoanalítica", prereq: ["teorias1"] },
  { id: "organiza", nombre: "Comportamiento Organizacional", prereq: ["social2", "teorias1", "teorias2"] },
  { id: "educativo", nombre: "Factores Educativos", prereq: ["evolutiva2", "teorias1", "teorias2"] },
  { id: "psicosociales", nombre: "Problemas Psicosociales", prereq: ["social2", "teorias1", "teorias2"] },
  { id: "integracion", nombre: "Integración en Psicología", prereq: ["teorias1", "teorias2"] },
  { id: "cognitiva", nombre: "Psicoterapia Cognitiva", prereq: ["teorias2"] },
  { id: "humanista", nombre: "Psicoterapia Humanista", prereq: ["teorias2"] },
  { id: "gestionorg", nombre: "Gestión de Organizaciones", prereq: ["organiza"] },
  { id: "gestionescolar", nombre: "Gestión Escolar", prereq: ["educativo"] },
  { id: "comunitaria", nombre: "Psicología Comunitaria", prereq: ["psicosociales"] },
  { id: "evolutiva2", nombre: "Psicología Evolutiva II", prereq: ["evolutiva1"] },
  { id: "electivoesp1", nombre: "Electivo Especialización I", prereq: [] },
  { id: "electivoesp2", nombre: "Electivo Especialización II", prereq: [] },
  { id: "electivoesp3", nombre: "Electivo Especialización III", prereq: [] },
  { id: "diseinterv", nombre: "Diseño e Intervención", prereq: [] },
  { id: "disecontexto", nombre: "Diseño en Contextos", prereq: [] },
  { id: "proyecto", nombre: "Proyecto de Investigación", prereq: ["cuantitativos"] },
  { id: "seminario", nombre: "Seminario de Investigación", prereq: ["estrategias", "seminario"] },
  { id: "practica", nombre: "Práctica Profesional", prereq: ["estrategias", "practica"] },
];

// Renderizar botones
const grid = document.getElementById("grid");
cursos.forEach(({ id, nombre, prereq }) => {
  const div =
